#!/bin/bash
# this script will be stored in $HOME/projet



#mkdir $HOME/recyclebin
if [[ ! -d $HOME/recyclebin ]]
then 
    mkdir $HOME/recyclebin
fi
#touch $HOME/.restore.info
if [[ ! -f $HOME/.restore.info ]]
then
    touch $HOME/.restore.info
fi


function optFunc(){
    interactive=False
    verbose=False
    recursive=False
    while getopts :ivr opt
    do
        case $opt in
            i) interactive=True;;
            v) verbose=True;;
            r) recursive=True;;
            *) echo bad option - $OPTARG
                echo Try 'recycle --help for more information.'
                exit 1;;
        esac

    done
}

function recyclingFiles(){
    inode=$(ls -i $PWD/$1| cut -d" " -f1)
    name=$1\_$inode
    mv $PWD/$1 $HOME/recyclebin/$name
    echo "$name:$PWD/$1" >> $HOME/.restore.info

}


function recycleFunc(){
    
    response="Y"  


    if [[ $# -eq 0 ]]
    then
        echo "error1:no filename provided"
        exit 1

    else
        for fileName in $*
        do
            if [[ ! -f $fileName ]]
            then
                echo "error2: File does not exist"
                exit 2

            elif [[ $fileName == "recycle" ]]
            then    
                echo "error4: Attempting to delete recycle - operation aborted"
                exit 3 

            elif [[ -d $fileName ]]
            then

                if $recursive
                then
                    
                    fullpaths=$(find $PWD/$fileName -type f)
                    for fullpath in $fullpaths:
                    do
                        inode=$(ls -i $fullpath | cut -d" " -f1)
                        fn=$(find $fullpath -type f| egrep -o "[/][^/]*$"|cut -d/ -f2)
                        name=$fn\_$inode
                        mv $fullpath $HOME/recyclebin/$name
                        echo "$name:$fullpath" >> $HOME/.restore.info
                    done
                else
                    echo "error3: Directory name provided"
                    exit 4 
                fi


            else 
                if $interactive
                then
                read -p "Do you want to recycle $fileName ? " userResponse
                response=$userResponse  
                fi 

                if [[ $response =~ ^[yY] ]]
                then
                
                    recyclingFiles $fileName
                    
                    if $verbose
                    then
                        echo "$fileName under the $PWD is deleted. The file reference number $name"
                    fi

                else
                    echo "do not recycle the file"
               fi
            fi
        done
    fi


}

optFunc $*
shift $[OPTIND-1]
recycleFunc $*

