#!/bin/bash


fileName=$1
if [[ $# -eq 0 ]]
then
    echo "error1:no filename provided"
    exit 1
elif [[ ! -f $HOME/recyclebin/$fileName ]]
then
    echo "file does not exist"
else
    restorePath=$(echo $(cat $HOME/.restore.info | grep $fileName | cut -d: -f2))
    pathname=$(echo $(cat $HOME/.restore.info | grep $fileName ))
    
    
    if [[ -f $restorePath ]]
    then
        read -p "Do you want to overwirte? y/n " response
        if [[ $response =~ ^[Yy] ]]
        then
            # echo "overwirte"
            # echo "$HOME/recyclebin/$fileName"
            # echo "$pathname"
            mv -f $HOME/recyclebin/$fileName $restorePath
            echo $pathname | tee /tmp/deletedStorage | echo "$(grep -vf /tmp/deletedStorage $HOME/.restore.info)" > $HOME/.restore.info
        else    
            echo "cancel restoring"
        fi
    else 
        # echo " not exists"
        mv $HOME/recyclebin/$fileName $restorePath
        echo $pathname | tee /tmp/deletedStorage.txt | echo "$(grep -vf /tmp/deletedStorage.txt $HOME/.restore.info)" > $HOME/.restore.info
    fi
fi
